ServerName localhost

DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    Require all granted
    AllowOverride None
</Directory>

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /index.html [L]

ProxyPreserveHost On
ProxyPass        /api http://backend:5000/api
ProxyPassReverse /api http://backend:5000/api
